name: darknet-reference
weights_url: https://pjreddie.com/media/files/darknet.weights
cfg_url: https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/darknet.cfg
labels_url: https://raw.githubusercontent.com/pjreddie/darknet/master/data/imagenet.shortnames.list
