name: yolov3
weights_url: https://pjreddie.com/media/files/yolov3.weights
cfg_url: https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3.cfg
labels_url: https://raw.githubusercontent.com/pjreddie/darknet/master/data/coco.names
