name: yolov2
weights_url: https://pjreddie.com/media/files/yolov2.weights
cfg_url: https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov2.cfg
labels_url: https://raw.githubusercontent.com/pjreddie/darknet/master/data/coco.names
